-- H2 建表 + 种子脚本：scaffold-audit 全表
-- 主键均由应用层雪花 ID 生成，与 V1__init_audit.sql 保持一致（无自增/序列）
-- audit_oper_log（操作日志，scaffold-audit 自有审计表，仅追加；扩展列用于等保 8.1.4 审计）
CREATE TABLE audit_oper_log (
    oper_id       BIGINT NOT NULL PRIMARY KEY,
    title         VARCHAR(500),
    business_type INT,
    method        VARCHAR(200),
    request_method VARCHAR(10),
    operator_type INT,
    oper_name     VARCHAR(50),
    dept_name     VARCHAR(200),
    oper_url      VARCHAR(255),
    oper_ip       VARCHAR(128),
    oper_param    VARCHAR(2000),
    json_result   VARCHAR(2000),
    status        INT,
    error_msg     VARCHAR(2000),
    oper_time     TIMESTAMP,
    cost_time     BIGINT,
    user_id       BIGINT,
    session_id    VARCHAR(100),
    biz_key       VARCHAR(100),
    biz_type      VARCHAR(50),
    event_type    VARCHAR(50),
    result_code   VARCHAR(20),
    request_ip    VARCHAR(128),
    before_value  VARCHAR(2000),
    after_value   VARCHAR(2000)
);

-- sys_role（system 域只读授权表，支持 del_flag + status，供 AuditLogMapper.selectUserRoles 使用）
CREATE TABLE sys_role (
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50),
    role_key  VARCHAR(100),
    del_flag  CHAR(1) DEFAULT '0',
    status    CHAR(1) DEFAULT '0'
);

-- sys_user_role（system 域只读授权表，关联表）
CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id  BIGINT
);

-- collector_audit_log
CREATE TABLE collector_audit_log (
    id              BIGINT NOT NULL PRIMARY KEY,
    domain          VARCHAR(100),
    source          VARCHAR(100),
    channel_type    VARCHAR(50),
    status          VARCHAR(20),
    record_count    BIGINT,
    watermark_before VARCHAR(100),
    watermark_after  VARCHAR(100),
    error_msg       VARCHAR(1000),
    cost_ms         BIGINT,
    start_time      TIMESTAMP,
    create_time     TIMESTAMP
);

-- query_audit_log
CREATE TABLE query_audit_log (
    id               BIGINT NOT NULL PRIMARY KEY,
    caller_system    VARCHAR(100),
    operator_name    VARCHAR(100),
    subject_uid      VARCHAR(100),
    subject_masked   VARCHAR(100),
    query_type       VARCHAR(50),
    purpose          VARCHAR(200),
    request_id       VARCHAR(100),
    result_count     BIGINT,
    result_summary   VARCHAR(500),
    query_time       TIMESTAMP
);

-- sys_config（system 域只读授权表，供 AuditLogMapper.selectSecurityConfig 使用）
CREATE TABLE sys_config (
    config_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100),
    config_key  VARCHAR(100),
    config_value VARCHAR(500),
    config_type CHAR(1) DEFAULT 'N'
);

-- audit_logininfor（登录日志，scaffold-audit 自有审计表，仅追加；供 selectLogininforList / selectLoginFailTop10 使用）
CREATE TABLE audit_logininfor (
    info_id     BIGINT NOT NULL PRIMARY KEY,
    user_name   VARCHAR(100),
    ipaddr      VARCHAR(128),
    status      CHAR(1),
    msg         VARCHAR(500),
    access_time TIMESTAMP
);

INSERT INTO sys_config (config_name, config_key, config_value, config_type) VALUES ('密码策略-最小长度', 'sys.account.password.minLength', '8', 'Y');
INSERT INTO sys_config (config_name, config_key, config_value, config_type) VALUES ('密码策略-最大长度', 'sys.account.password.maxLength', '20', 'Y');

-- audit_logininfor 种子：id=1 失败（供 selectLoginFailTop10），id=2 成功
INSERT INTO audit_logininfor (info_id, user_name, ipaddr, status, msg, access_time)
VALUES (1, 'admin', '127.0.0.1', '1', '密码错误', CURRENT_TIMESTAMP);
INSERT INTO audit_logininfor (info_id, user_name, ipaddr, status, msg, access_time)
VALUES (2, 'admin', '10.0.0.1', '0', '登录成功', CURRENT_TIMESTAMP);

-- 种子数据
INSERT INTO audit_oper_log (oper_id, title, business_type, oper_name, status, event_type, biz_key, user_id, oper_time, cost_time)
VALUES (1, '用户登录', 1, 'admin', 0, 'LOGIN', 'user:1', 1, CURRENT_TIMESTAMP, 150);

INSERT INTO audit_oper_log (oper_id, title, business_type, oper_name, status, event_type, biz_key, user_id, oper_time, cost_time)
VALUES (2, '角色授权', 2, 'admin', 0, 'ROLE_ASSIGN', 'user:1', 1, CURRENT_TIMESTAMP, 80);

INSERT INTO audit_oper_log (oper_id, title, business_type, oper_name, status, event_type, biz_key, user_id, oper_time, cost_time)
VALUES (3, '权限变更', 3, 'admin', 0, 'PERM_CHANGE', 'user:2', 1, CURRENT_TIMESTAMP, 60);

-- biz_key 不是 "user:" 开头，不被 filterByBizKey 命中
INSERT INTO audit_oper_log (oper_id, title, business_type, oper_name, status, event_type, biz_key, user_id, oper_time, cost_time)
VALUES (4, '系统配置', 6, 'admin', 0, 'CONFIG_CHANGE', 'config:sys', 1, CURRENT_TIMESTAMP, 30);

INSERT INTO sys_role (role_id, role_name, role_key, del_flag, status) VALUES (1, '管理员', 'admin', '0', '0');
INSERT INTO sys_role (role_id, role_name, role_key, del_flag, status) VALUES (2, '普通用户', 'common', '0', '0');
INSERT INTO sys_role (role_id, role_name, role_key, del_flag, status) VALUES (3, '已删除角色', 'deleted', '2', '0');

INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 2);

INSERT INTO collector_audit_log (id, domain, source, channel_type, status, record_count, create_time)
VALUES (100, 'tourist', 'file', 'csv', 'success', 1000, CURRENT_TIMESTAMP);

INSERT INTO query_audit_log (id, caller_system, operator_name, subject_uid, query_type, request_id, result_count)
VALUES (100, 'ct-web', 'admin', 'uid-001', 'person_query', 'req-123', 50);

ALTER TABLE sys_role ALTER COLUMN role_id RESTART WITH 100;
ALTER TABLE sys_config ALTER COLUMN config_id RESTART WITH 100;

-- audit_trace（V2：全链路业务留痕，主键应用侧雪花）
CREATE TABLE audit_trace (
    trace_id      BIGINT          NOT NULL,
    scene         VARCHAR(64)     NOT NULL,
    biz_type      VARCHAR(64),
    biz_id        VARCHAR(64),
    operator      VARCHAR(64),
    operate_ip    VARCHAR(64),
    terminal      VARCHAR(32),
    method_name   VARCHAR(256),
    snapshot_json CLOB,
    result_json   CLOB,
    error_msg     VARCHAR(1000),
    cost_ms       BIGINT,
    key_action    CHAR(1)         DEFAULT '0',
    prev_digest   VARCHAR(64),
    curr_digest   VARCHAR(64)     NOT NULL,
    sign_value    VARCHAR(512),
    op_time       TIMESTAMP       NOT NULL,
    create_time   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_audit_trace PRIMARY KEY (trace_id)
);

-- A7 列级补齐（对照 V3__audit_columns.sql）
ALTER TABLE audit_logininfor ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE audit_logininfor ADD COLUMN IF NOT EXISTS device_info VARCHAR(255);
ALTER TABLE audit_logininfor ADD COLUMN IF NOT EXISTS session_id VARCHAR(64);
ALTER TABLE audit_oper_log ADD COLUMN IF NOT EXISTS request_id VARCHAR(64);
