-- ============================================================================
-- Oracle 版本: V1__init_quartz.sql
-- 转换自: ct-modules/scaffold-job/src/main/resources/db/migration/V1__init_quartz.sql
-- 说明: Quartz 调度表（Oracle 兼容版本）
--   1. VARCHAR → VARCHAR2, BIGINT → NUMBER, BLOB → BLOB 保持不变
--   2. 外键语法在 Oracle 中稍有不同
--   3. ENGINE=InnoDB 在 Oracle 中不需要
-- ============================================================================

-- 1、任务详细信息表
CREATE TABLE JOB_DB.QRTZ_JOB_DETAILS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    JOB_NAME         VARCHAR2(200) NOT NULL,
    JOB_GROUP        VARCHAR2(200) NOT NULL,
    DESCRIPTION      VARCHAR2(250),
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL,
    IS_DURABLE       VARCHAR2(1)   NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1)  NOT NULL,
    IS_UPDATE_DATA   VARCHAR2(1)  NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1)  NOT NULL,
    JOB_DATA         BLOB,
    CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
COMMENT ON TABLE JOB_DB.QRTZ_JOB_DETAILS IS '任务详细信息表';

-- 2、触发器详细信息表
CREATE TABLE JOB_DB.QRTZ_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    JOB_NAME         VARCHAR2(200) NOT NULL,
    JOB_GROUP        VARCHAR2(200) NOT NULL,
    DESCRIPTION      VARCHAR2(250),
    NEXT_FIRE_TIME   NUMBER(13),
    PREV_FIRE_TIME   NUMBER(13),
    PRIORITY         INTEGER,
    TRIGGER_STATE    VARCHAR2(16)  NOT NULL,
    TRIGGER_TYPE     VARCHAR2(8)   NOT NULL,
    START_TIME       NUMBER(13)   NOT NULL,
    END_TIME         NUMBER(13),
    CALENDAR_NAME    VARCHAR2(200),
    MISFIRE_INSTR    SMALLINT,
    JOB_DATA         BLOB,
    CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
COMMENT ON TABLE JOB_DB.QRTZ_TRIGGERS IS '触发器详细信息表';

-- 外键
ALTER TABLE JOB_DB.QRTZ_TRIGGERS ADD CONSTRAINT FK_QRTZ_TRIGGERS_JD
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES JOB_DB.QRTZ_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP);

-- 3、简单触发器信息表
CREATE TABLE JOB_DB.QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    REPEAT_COUNT     NUMBER(7)    NOT NULL,
    REPEAT_INTERVAL  NUMBER(12)   NOT NULL,
    TIMES_TRIGGERED  NUMBER(10)   NOT NULL,
    CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE JOB_DB.QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPLE_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES JOB_DB.QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 4、Cron 触发器表
CREATE TABLE JOB_DB.QRTZ_CRON_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION  VARCHAR2(200) NOT NULL,
    TIME_ZONE_ID     VARCHAR2(80),
    CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE JOB_DB.QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_QRTZ_CRON_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES JOB_DB.QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 5、Blob 类型触发器表
CREATE TABLE JOB_DB.QRTZ_BLOB_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    BLOB_DATA        BLOB,
    CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE JOB_DB.QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_QRTZ_BLOB_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES JOB_DB.QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 6、日历信息表
CREATE TABLE JOB_DB.QRTZ_CALENDARS (
    SCHED_NAME     VARCHAR2(120) NOT NULL,
    CALENDAR_NAME  VARCHAR2(200) NOT NULL,
    CALENDAR       BLOB          NOT NULL,
    CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);
COMMENT ON TABLE JOB_DB.QRTZ_CALENDARS IS '日历信息表';

-- 7、暂停的触发器表
CREATE TABLE JOB_DB.QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME     VARCHAR2(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);
COMMENT ON TABLE JOB_DB.QRTZ_PAUSED_TRIGGER_GRPS IS '暂停的触发器表';

-- 8、已触发的触发器表
CREATE TABLE JOB_DB.QRTZ_FIRED_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    ENTRY_ID         VARCHAR2(95)  NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    INSTANCE_NAME    VARCHAR2(200) NOT NULL,
    FIRED_TIME      NUMBER(13)    NOT NULL,
    SCHED_TIME      NUMBER(13)    NOT NULL,
    PRIORITY         INTEGER       NOT NULL,
    STATE            VARCHAR2(16) NOT NULL,
    JOB_NAME         VARCHAR2(200),
    JOB_GROUP        VARCHAR2(200),
    IS_NONCONCURRENT VARCHAR2(1),
    REQUESTS_RECOVERY VARCHAR2(1),
    CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);
COMMENT ON TABLE JOB_DB.QRTZ_FIRED_TRIGGERS IS '已触发的触发器表';

-- 9、调度器状态表
CREATE TABLE JOB_DB.QRTZ_SCHEDULER_STATE (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    INSTANCE_NAME    VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13)  NOT NULL,
    CHECKIN_INTERVAL  NUMBER(13)   NOT NULL,
    CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);
COMMENT ON TABLE JOB_DB.QRTZ_SCHEDULER_STATE IS '调度器状态表';

-- 10、悲观锁信息表
CREATE TABLE JOB_DB.QRTZ_LOCKS (
    SCHED_NAME   VARCHAR2(120) NOT NULL,
    LOCK_NAME    VARCHAR2(40)  NOT NULL,
    CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
COMMENT ON TABLE JOB_DB.QRTZ_LOCKS IS '存储的悲观锁信息表';

-- 11、同步机制的行锁表
CREATE TABLE JOB_DB.QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME       VARCHAR2(120) NOT NULL,
    TRIGGER_NAME     VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP    VARCHAR2(200) NOT NULL,
    STR_PROP_1       VARCHAR2(512),
    STR_PROP_2       VARCHAR2(512),
    STR_PROP_3       VARCHAR2(512),
    INT_PROP_1       INTEGER,
    INT_PROP_2       INTEGER,
    LONG_PROP_1      NUMBER,
    LONG_PROP_2      NUMBER,
    DEC_PROP_1       NUMBER(13,4),
    DEC_PROP_2        NUMBER(13,4),
    BOOL_PROP_1       VARCHAR2(1),
    BOOL_PROP_2       VARCHAR2(1),
    CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE JOB_DB.QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPROP_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES JOB_DB.QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

COMMIT;

-- ===================================================================
-- 以下并入原 V2__init_job_data.sql（占位）与 V3__create_sys_job_tables.sql（2026-09 合并为单基线）
-- 定时任务初始化数据：暂无生效语句；Quartz 持久化 Job 注册示例注释见原 V2__init_job_data.sql（已并入）


-- ===================================================================
CREATE TABLE JOB_DB.SYS_JOB (
    JOB_ID              NUMBER(20) GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    JOB_NAME            VARCHAR2(64)  DEFAULT '',
    JOB_GROUP           VARCHAR2(64) DEFAULT 'DEFAULT',
    INVOKE_TARGET       VARCHAR2(500) NOT NULL,
    CRON_EXPRESSION     VARCHAR2(255) DEFAULT '',
    MISFIRE_POLICY      VARCHAR2(20)  DEFAULT '3',
    CONCURRENT          CHAR(1)       DEFAULT '1',
    STATUS              CHAR(1)       DEFAULT '0',
    CREATE_BY           VARCHAR2(64)  DEFAULT '',
    CREATE_TIME         TIMESTAMP(0),
    UPDATE_BY           VARCHAR2(64)  DEFAULT '',
    UPDATE_TIME         TIMESTAMP(0),
    REMARK              VARCHAR2(500) DEFAULT '',
    VERSION             NUMBER(10)    DEFAULT 0,
    CONSTRAINT PK_SYS_JOB PRIMARY KEY (JOB_ID, JOB_NAME, JOB_GROUP)
);

CREATE TABLE JOB_DB.SYS_JOB_LOG (
    JOB_LOG_ID      NUMBER(20) GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 1),
    JOB_NAME        VARCHAR2(64)   NOT NULL,
    JOB_GROUP       VARCHAR2(64)   NOT NULL,
    INVOKE_TARGET   VARCHAR2(500)  NOT NULL,
    JOB_MESSAGE     VARCHAR2(500),
    STATUS          CHAR(1)        DEFAULT '0',
    EXCEPTION_INFO  VARCHAR2(2000) DEFAULT '',
    START_TIME      TIMESTAMP(0),
    END_TIME        TIMESTAMP(0),
    CREATE_TIME     TIMESTAMP(0),
    CONSTRAINT PK_SYS_JOB_LOG PRIMARY KEY (JOB_LOG_ID)
);
