-- services/message mysql 方言家族基线（由 scripts/gen_dialect_migrations.py 从 h2 基线生成，勿手工编辑；
-- GENERATED-BY gen_dialect_migrations.py
-- 修正应改脚本映射表后 --force 重新生成；真实库接入回归见 docs/multi-database-guide.md §6）

-- 本地 H2 基线（对照 db/migration/oracle/V1__baseline.sql，H2 方言，去 schema 前缀）
-- 另建 SYSTEM_DB 模拟 schema（sys_user/sys_role/sys_user_role），供 UserDirectoryMapper 接收范围展开


CREATE TABLE msg_sms_channel (
    ID BIGINT,
    PRIMARY KEY (ID),
    CHANNEL_NAME VARCHAR(64) NOT NULL,
    CHANNEL_TYPE VARCHAR(20) NOT NULL,
    ACCESS_KEY VARCHAR(128) DEFAULT '',
    SECRET_KEY VARCHAR(256) DEFAULT '',
    SIGN_NAME VARCHAR(64) DEFAULT '',
    ENDPOINT VARCHAR(128),
    REGION VARCHAR(64),
    PRIORITY INT DEFAULT 1,
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_CHANNEL_NAME UNIQUE (CHANNEL_NAME)
) ENGINE=InnoDB;
CREATE INDEX IDX_MSG_SMS_CHANNEL_TYPE ON msg_sms_channel (CHANNEL_TYPE, STATUS);


CREATE TABLE msg_sms_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE VARCHAR(64) NOT NULL,
    TEMPLATE_NAME VARCHAR(64) NOT NULL,
    CHANNEL_ID BIGINT,
    TEMPLATE_MODE CHAR(1) DEFAULT '0',
    VENDOR_CODE VARCHAR(64),
    SIGN_NAME VARCHAR(64),
    TEMPLATE_CONTENT VARCHAR(1000) NOT NULL,
    PARAM_NAMES VARCHAR(512),
    CATEGORY VARCHAR(20),
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
) ENGINE=InnoDB;


CREATE TABLE msg_sms_log (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE VARCHAR(64) NOT NULL,
    CHANNEL_ID BIGINT,
    CHANNEL_TYPE VARCHAR(20),
    MOBILE VARCHAR(20) NOT NULL,
    SIGN_NAME VARCHAR(64),
    CONTENT VARCHAR(1000),
    PARAM_JSON VARCHAR(2000),
    SEND_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CHANNEL_MSG_ID VARCHAR(64),
    FAIL_REASON VARCHAR(512),
    RETRY_COUNT INT DEFAULT 0,
    SEND_TIME DATETIME,
    RECEIPT_TIME DATETIME,
    BIZ_TYPE VARCHAR(32),
    BIZ_ID VARCHAR(64),
    IDEMPOTENT_KEY VARCHAR(64),
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
) ENGINE=InnoDB;
CREATE INDEX IDX_MSG_SMS_LOG_SEND_TIME ON msg_sms_log (SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_MOBILE ON msg_sms_log (MOBILE, SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_STATUS ON msg_sms_log (SEND_STATUS, SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_MSG_ID ON msg_sms_log (CHANNEL_MSG_ID);


CREATE TABLE msg_mail_account (
    ID BIGINT,
    PRIMARY KEY (ID),
    ACCOUNT_NAME VARCHAR(64) NOT NULL,
    EMAIL_ADDR VARCHAR(128) NOT NULL,
    SMTP_HOST VARCHAR(128) NOT NULL,
    SMTP_PORT INT,
    SMTP_SSL CHAR(1) DEFAULT '1',
    AUTH_USER VARCHAR(128) NOT NULL,
    AUTH_CODE VARCHAR(256) NOT NULL,
    NICK_NAME VARCHAR(64),
    DAILY_LIMIT INT DEFAULT 0,
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_ACCOUNT_ADDR UNIQUE (EMAIL_ADDR)
) ENGINE=InnoDB;


CREATE TABLE msg_mail_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE VARCHAR(64) NOT NULL,
    TEMPLATE_NAME VARCHAR(64) NOT NULL,
    ACCOUNT_ID BIGINT,
    SUBJECT VARCHAR(200) NOT NULL,
    TEMPLATE_CONTENT LONGTEXT NOT NULL,
    IS_HTML CHAR(1) DEFAULT '1',
    PARAM_NAMES VARCHAR(512),
    CATEGORY VARCHAR(20),
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
) ENGINE=InnoDB;


CREATE TABLE msg_mail_log (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE VARCHAR(64),
    ACCOUNT_ID BIGINT,
    TO_ADDRS VARCHAR(1000) NOT NULL,
    CC_ADDRS VARCHAR(1000),
    SUBJECT VARCHAR(200),
    CONTENT LONGTEXT,
    IS_HTML CHAR(1) DEFAULT '1',
    ATTACH_FILE_IDS VARCHAR(500),
    SEND_STATUS VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    FAIL_REASON VARCHAR(512),
    RETRY_COUNT INT DEFAULT 0,
    SEND_TIME DATETIME,
    BIZ_TYPE VARCHAR(32),
    BIZ_ID VARCHAR(64),
    IDEMPOTENT_KEY VARCHAR(64),
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
) ENGINE=InnoDB;
CREATE INDEX IDX_MSG_MAIL_LOG_SEND_TIME ON msg_mail_log (SEND_TIME);
CREATE INDEX IDX_MSG_MAIL_LOG_STATUS ON msg_mail_log (SEND_STATUS, SEND_TIME);


CREATE TABLE msg_inner_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE VARCHAR(64) NOT NULL,
    TEMPLATE_NAME VARCHAR(64) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    TEMPLATE_CONTENT VARCHAR(2000) NOT NULL,
    MISSING_PARAM_MODE CHAR(1) DEFAULT '0',
    JUMP_URL VARCHAR(256),
    PARAM_NAMES VARCHAR(512),
    CATEGORY VARCHAR(20),
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_INNER_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
) ENGINE=InnoDB;


CREATE TABLE msg_inner_message (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE VARCHAR(64),
    TITLE VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    JUMP_URL VARCHAR(256),
    RECEIVER_ID BIGINT NOT NULL,
    RECEIVER_NAME VARCHAR(64),
    READ_FLAG CHAR(1) DEFAULT '0',
    READ_TIME DATETIME,
    SENDER_TYPE CHAR(1) DEFAULT '0',
    SENDER_ID BIGINT,
    SENDER_NAME VARCHAR(64),
    BIZ_TYPE VARCHAR(32),
    BIZ_ID VARCHAR(64),
    IDEMPOTENT_KEY VARCHAR(64),
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME,
    REMARK VARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_INNER_MSG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, RECEIVER_ID, IDEMPOTENT_KEY)
) ENGINE=InnoDB;
CREATE INDEX IDX_MSG_INNER_MSG_UNREAD ON msg_inner_message (RECEIVER_ID, READ_FLAG);
CREATE INDEX IDX_MSG_INNER_MSG_RECENT ON msg_inner_message (RECEIVER_ID, CREATE_TIME);

-- SYSTEM_DB 模拟 schema（UserDirectoryMapper 接收范围展开，只读）

CREATE TABLE sys_user (
    user_id BIGINT,
    PRIMARY KEY (user_id),
    user_name VARCHAR(64),
    nick_name VARCHAR(64),
    status CHAR(1) DEFAULT '0',
    del_flag CHAR(1) DEFAULT '0'
) ENGINE=InnoDB;

CREATE TABLE sys_role (
    role_id BIGINT,
    PRIMARY KEY (role_id),
    role_key VARCHAR(100),
    status CHAR(1) DEFAULT '0',
    del_flag CHAR(1) DEFAULT '0'
) ENGINE=InnoDB;

CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id BIGINT
) ENGINE=InnoDB;
