-- H2 (MODE=Oracle) 建表 + 种子脚本：sys_config
CREATE TABLE sys_config (
    config_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name VARCHAR(100)  NOT NULL,
    config_key  VARCHAR(100)  NOT NULL,
    config_value VARCHAR(500),
    config_type CHAR(1)      DEFAULT 'N',
    create_by   VARCHAR(64),
    create_time TIMESTAMP,
    update_by   VARCHAR(64),
    update_time TIMESTAMP,
    remark      VARCHAR(500),
    version     BIGINT DEFAULT 0
);

INSERT INTO sys_config (config_id, config_name, config_key, config_value, config_type, remark)
VALUES (1, '主框架页-默认皮肤样式名称', 'sys.index.skinName', 'skin-blue', 'Y', '皮肤配置');

INSERT INTO sys_config (config_id, config_name, config_key, config_value, config_type, remark)
VALUES (2, '用户管理-账号初始密码', 'sys.user.initPassword', '123456', 'Y', '初始密码');

INSERT INTO sys_config (config_id, config_name, config_key, config_value, config_type, remark)
VALUES (3, '主框架页-侧边栏主题', 'sys.index.sideTheme', 'theme-dark', 'Y', '侧边栏主题');

ALTER TABLE sys_config ALTER COLUMN config_id RESTART WITH 100;
