-- H2 (MODE=Oracle) 建表 + 种子脚本：sys_post
CREATE TABLE sys_post (
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_code   VARCHAR(64)   NOT NULL,
    post_name   VARCHAR(50)   NOT NULL,
    post_sort   INT          NOT NULL,
    status      CHAR(1)      DEFAULT '0',
    create_by   VARCHAR(64),
    create_time TIMESTAMP,
    update_by   VARCHAR(64),
    update_time TIMESTAMP,
    remark      VARCHAR(500),
    version     BIGINT DEFAULT 0
);

INSERT INTO sys_post (post_id, post_code, post_name, post_sort, status, remark)
VALUES (1, 'ceo',   '董事长',    1, '0', '最高管理岗');

INSERT INTO sys_post (post_id, post_code, post_name, post_sort, status, remark)
VALUES (2, 'se',    '项目经理',  2, '0', '技术管理岗');

INSERT INTO sys_post (post_id, post_code, post_name, post_sort, status, remark)
VALUES (3, 'dev',   '开发工程师', 3, '1', '已停用');

ALTER TABLE sys_post ALTER COLUMN post_id RESTART WITH 100;
