-- H2 建表 + 种子脚本：scaffold-system 关联表
-- sys_role_dept（角色-部门关联）
CREATE TABLE sys_role_dept (
    role_id BIGINT NOT NULL,
    dept_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, dept_id)
);

-- sys_user_role（用户-角色关联）
CREATE TABLE sys_user_role (
    user_id BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);

-- sys_role_menu（角色-菜单关联）
CREATE TABLE sys_role_menu (
    role_id BIGINT NOT NULL,
    menu_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id)
);

-- sys_user_post（用户-岗位关联）
CREATE TABLE sys_user_post (
    user_id BIGINT NOT NULL,
    post_id  BIGINT NOT NULL,
    PRIMARY KEY (user_id, post_id)
);

-- sys_user_identity（用户第三方绑定）
CREATE TABLE sys_user_identity (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    idp_type    VARCHAR(50),
    idp_uid     VARCHAR(255),
    extra       VARCHAR(500),
    status      CHAR(1) DEFAULT '0',
    create_time TIMESTAMP
);

-- sys_user_password_history（密码历史）
CREATE TABLE sys_user_password_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    password    VARCHAR(200),
    create_time TIMESTAMP
);

-- 种子数据
INSERT INTO sys_role_dept (role_id, dept_id) VALUES (1, 100);
INSERT INTO sys_role_dept (role_id, dept_id) VALUES (1, 101);
INSERT INTO sys_role_dept (role_id, dept_id) VALUES (2, 100);

INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO sys_user_role (user_id, role_id) VALUES (1, 2);
INSERT INTO sys_user_role (user_id, role_id) VALUES (2, 1);

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 1);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 100);
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 1);

INSERT INTO sys_user_post (user_id, post_id) VALUES (1, 1);
INSERT INTO sys_user_post (user_id, post_id) VALUES (2, 2);

INSERT INTO sys_user_identity (user_id, idp_type, idp_uid, status)
VALUES (1, 'wechat', 'wx_openid_001', '0');

INSERT INTO sys_user_password_history (user_id, password)
VALUES (1, 'hashed_pwd_old');

ALTER TABLE sys_user_identity ALTER COLUMN id RESTART WITH 100;
ALTER TABLE sys_user_password_history ALTER COLUMN id RESTART WITH 100;
