-- =====================================================================
-- H2 (MODE=Oracle) Mapper 测试建表 + 种子脚本：sys_user 相关最小列集
-- 列集对照生产 flyway 脚本 db/migration/h2/V1__init_system.sql
-- =====================================================================

CREATE TABLE sys_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id BIGINT,
    user_name VARCHAR(30),
    nick_name VARCHAR(30),
    email VARCHAR(50),
    phonenumber VARCHAR(20),
    sex CHAR(1),
    avatar VARCHAR(100),
    password VARCHAR(100),
    status CHAR(1) DEFAULT '0',
    del_flag CHAR(1) DEFAULT '0',
    login_ip VARCHAR(128),
    login_date TIMESTAMP,
    pwd_update_date TIMESTAMP,
    create_by VARCHAR(64),
    create_time TIMESTAMP,
    update_by VARCHAR(64),
    update_time TIMESTAMP,
    remark VARCHAR(500),
    version BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE sys_dept (
    dept_id BIGINT PRIMARY KEY,
    parent_id BIGINT,
    ancestors VARCHAR(500),
    dept_name VARCHAR(30),
    order_num INT,
    leader VARCHAR(20),
    status CHAR(1)
);

CREATE TABLE sys_role (
    role_id BIGINT PRIMARY KEY,
    role_name VARCHAR(30),
    role_key VARCHAR(30),
    role_sort INT,
    data_scope CHAR(1),
    status CHAR(1),
    del_flag CHAR(1) DEFAULT '0'
);

CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id BIGINT
);

-- ---------------------------------------------------------------------
-- 种子数据
-- ---------------------------------------------------------------------
INSERT INTO sys_dept VALUES (100, 0, '0', '研发部门', 1, '张三', '0');
INSERT INTO sys_role VALUES (1, '超级管理员', 'admin', 1, '1', '0', '0');
INSERT INTO sys_role VALUES (2, '普通角色', 'common', 2, '2', '0', '0');
INSERT INTO sys_user(user_id, dept_id, user_name, nick_name, password, status, del_flag, version)
VALUES (1, 100, 'admin', '管理员', '{sm3}seed', '0', '0', 0);
INSERT INTO sys_user(user_id, dept_id, user_name, nick_name, password, status, del_flag, version)
VALUES (2, 100, 'tester', '测试员', '{sm3}test', '0', '0', 0);
INSERT INTO sys_user_role VALUES (1, 1);
INSERT INTO sys_user_role VALUES (1, 2);
INSERT INTO sys_user_role VALUES (2, 1);

-- 种子数据用了显式主键，把 identity 序列推到种子之后
-- （迁移导数时同样要对齐序列）
ALTER TABLE sys_user ALTER COLUMN user_id RESTART WITH 1000;
