-- 公告已读记录建表 + 种子
CREATE TABLE sys_notice_read (
    read_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id  BIGINT,
    user_id    BIGINT,
    read_time  TIMESTAMP
);

INSERT INTO sys_notice_read (read_id, notice_id, user_id, read_time)
VALUES
(1, 1, 1, CURRENT_TIMESTAMP),
(2, 2, 1, CURRENT_TIMESTAMP);

ALTER TABLE sys_notice_read ALTER COLUMN read_id RESTART WITH 100;
