-- H2 建表 + 种子脚本：sys_dict_type
CREATE TABLE sys_dict_type (
    dict_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_name   VARCHAR(100) NOT NULL,
    dict_type   VARCHAR(100) NOT NULL,
    status      CHAR(1)      DEFAULT '0',
    create_by   VARCHAR(64),
    create_time TIMESTAMP,
    update_by   VARCHAR(64),
    update_time TIMESTAMP,
    remark      VARCHAR(500),
    version     BIGINT DEFAULT 0
);

INSERT INTO sys_dict_type (dict_id, dict_name, dict_type, status, remark)
VALUES (1, '用户性别', 'sys_user_sex', '0', '性别列表');

INSERT INTO sys_dict_type (dict_id, dict_name, dict_type, status, remark)
VALUES (2, '菜单状态', 'sys_show_hide', '0', '菜单状态列表');

INSERT INTO sys_dict_type (dict_id, dict_name, dict_type, status, remark)
VALUES (3, '系统开关', 'sys_normal_disable', '0', '系统开关列表');

ALTER TABLE sys_dict_type ALTER COLUMN dict_id RESTART WITH 100;
