-- =====================================================================
-- H2 (MODE=Oracle) Mapper 测试建表 + 种子脚本：sys_user / sys_dept / sys_role
-- 列集对照生产 flyway 脚本 db/migration/h2/V1__init_system.sql
-- 用于 SysUserMapperTest，验证 selectUserList / selectAllocatedList / selectUnallocatedList
-- =====================================================================

CREATE TABLE sys_dept (
    dept_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    ancestors   VARCHAR(500),
    dept_name   VARCHAR(30),
    order_num   INT,
    leader      VARCHAR(20),
    phone       VARCHAR(20),
    email       VARCHAR(50),
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64),
    create_time TIMESTAMP,
    version     BIGINT DEFAULT 0
);

CREATE TABLE sys_role (
    role_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name          VARCHAR(30),
    role_key           VARCHAR(100),
    role_sort          INT,
    data_scope         CHAR(1),
    menu_check_strictly CHAR(1),
    dept_check_strictly CHAR(1),
    status             CHAR(1) DEFAULT '0',
    del_flag           CHAR(1) DEFAULT '0',
    create_by          VARCHAR(64),
    create_time        TIMESTAMP,
    version            BIGINT DEFAULT 0
);

CREATE TABLE sys_user (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id         BIGINT,
    user_name       VARCHAR(30),
    nick_name       VARCHAR(30),
    email           VARCHAR(50),
    phonenumber     VARCHAR(20),
    sex             CHAR(1),
    avatar          VARCHAR(100),
    password        VARCHAR(100),
    status          CHAR(1) DEFAULT '0',
    del_flag        CHAR(1) DEFAULT '0',
    login_ip        VARCHAR(128),
    login_date      TIMESTAMP,
    pwd_update_date TIMESTAMP,
    create_by       VARCHAR(64),
    create_time     TIMESTAMP,
    update_by       VARCHAR(64),
    update_time     TIMESTAMP,
    remark          VARCHAR(500),
    version         BIGINT DEFAULT 0
);

CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id BIGINT
);

-- ---------------------------------------------------------------------
-- 种子数据：dept 树用于 find_in_set 测试
-- dept 100 = 研发部，children 101/102；dept 200 = 运维部
-- ---------------------------------------------------------------------
INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, status, del_flag)
VALUES (100, 0, '0', '研发部', 1, '0', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, status, del_flag)
VALUES (101, 100, '0,100', '研发一组', 1, '0', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, status, del_flag)
VALUES (102, 100, '0,100', '研发二组', 2, '0', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, status, del_flag)
VALUES (200, 0, '0', '运维部', 2, '0', '0');

-- ---------------------------------------------------------------------
-- 种子数据：4 个角色（不同 status）
-- ---------------------------------------------------------------------
INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (1, '管理员', 'admin', 1, '1', '0', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (2, '开发', 'dev', 2, '2', '0', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (3, '访客', 'guest', 3, '2', '0', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (4, '停用角色', 'disabled_role', 4, '2', '1', '0');

-- ---------------------------------------------------------------------
-- 种子数据：6 个用户（不同 dept/status/del_flag/phone）
-- userId 1-5: del_flag='0'
-- userId 6: del_flag='2' (已删除)
-- userId 7: del_flag='0', status='1' (停用)
-- ---------------------------------------------------------------------
INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (1, 100, 'admin', '系统管理员', 'admin@ct.com', '13800000001', '0', '0', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (2, 101, 'dev001', '开发者甲', 'dev001@ct.com', '13800000002', '0', '0', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (3, 102, 'dev002', '开发者乙', 'dev002@ct.com', '13800000003', '0', '0', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (4, 200, 'ops001', '运维人员', 'ops001@ct.com', '13800000004', '0', '0', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (5, 100, 'guest001', '访客用户', 'guest001@ct.com', '13800000005', '0', '0', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (6, 100, 'deleted', '已删除用户', 'del@ct.com', '13800000006', '0', '2', 0);

INSERT INTO sys_user (user_id, dept_id, user_name, nick_name, email, phonenumber, status, del_flag, version)
VALUES (7, 101, 'disabled', '停用用户', 'disabled@ct.com', '13800000007', '1', '0', 0);

-- ---------------------------------------------------------------------
-- 角色分配（user_role）
-- roleId=1 (admin): userId=1
-- roleId=2 (dev):   userId=2, 3
-- roleId=3 (guest):  userId=5, 7
-- roleId=4 (disabled): userId=6, 7
-- userId=4 (ops) 无角色
-- ---------------------------------------------------------------------
INSERT INTO sys_user_role VALUES (1, 1);
INSERT INTO sys_user_role VALUES (2, 2);
INSERT INTO sys_user_role VALUES (3, 2);
INSERT INTO sys_user_role VALUES (5, 3);
INSERT INTO sys_user_role VALUES (6, 4);
INSERT INTO sys_user_role VALUES (7, 3);
INSERT INTO sys_user_role VALUES (7, 4);

-- identity 序列推到种子之后（导数迁移后同样要对齐）
ALTER TABLE sys_dept ALTER COLUMN dept_id RESTART WITH 1000;
ALTER TABLE sys_role ALTER COLUMN role_id RESTART WITH 1000;
ALTER TABLE sys_user ALTER COLUMN user_id RESTART WITH 1000;
