-- 菜单建表 + 种子数据
-- menu_type: M=目录 C=菜单 F=按钮
-- is_frame: 0=内部 1=外链
-- is_cache: 0=不缓存 1=缓存
-- visible: 0=显示 1=隐藏
-- status: 0=正常 1=停用
CREATE TABLE sys_menu (
    menu_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name    VARCHAR(100),
    parent_id    BIGINT DEFAULT 0,
    order_num    INT,
    path         VARCHAR(255),
    component    VARCHAR(255),
    query        VARCHAR(255),
    route_name   VARCHAR(255),
    is_frame     CHAR(1) DEFAULT '1',
    is_cache     CHAR(1) DEFAULT '1',
    menu_type    VARCHAR(1),
    visible      CHAR(1) DEFAULT '0',
    status       CHAR(1) DEFAULT '0',
    perms        VARCHAR(100),
    icon         VARCHAR(100),
    create_by    VARCHAR(64),
    create_time  TIMESTAMP,
    update_by    VARCHAR(64),
    update_time  TIMESTAMP,
    remark       VARCHAR(500),
    version      BIGINT DEFAULT 0
);

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark, version)
VALUES (1, '系统管理', 0, 1, 'system', NULL, NULL, NULL, '1', '1', 'M', '0', '0', NULL, 'system', 'admin', CURRENT_TIMESTAMP, '系统管理目录', 1);

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark, version)
VALUES (100, '用户管理', 1, 1, 'user', 'system/user/index', NULL, 'User', '1', '0', 'C', '0', '0', 'system:user:list', 'user', 'admin', CURRENT_TIMESTAMP, '用户管理菜单', 1);

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark, version)
VALUES (101, '角色管理', 1, 2, 'role', 'system/role/index', NULL, 'Role', '1', '0', 'C', '0', '0', 'system:role:list', 'peoples', 'admin', CURRENT_TIMESTAMP, '角色管理菜单', 1);

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, remark, version)
VALUES (102, '菜单管理', 1, 3, 'menu', 'system/menu/index', NULL, 'Menu', '1', '0', 'C', '0', '1', 'system:menu:list', 'tree-table', 'admin', CURRENT_TIMESTAMP, '菜单管理菜单（停用）', 1);

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, query, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, version)
VALUES (200, '用户新增', 100, 1, 'add', NULL, 'roleId=100', NULL, '1', '1', 'F', '0', '0', 'system:user:add', '#', 'admin', CURRENT_TIMESTAMP, 1);

ALTER TABLE sys_menu ALTER COLUMN menu_id RESTART WITH 1000;
