-- H2 建表 + 种子脚本：sys_notice
CREATE TABLE sys_notice (
    notice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_title   VARCHAR(100) NOT NULL,
    notice_type    CHAR(1)      NOT NULL,
    notice_content VARCHAR(2000),
    status        CHAR(1)      DEFAULT '0',
    create_by     VARCHAR(64),
    create_time   TIMESTAMP,
    update_by     VARCHAR(64),
    update_time   TIMESTAMP,
    remark        VARCHAR(500),
    version       BIGINT DEFAULT 0
);

INSERT INTO sys_notice (notice_id, notice_title, notice_type, notice_content, status, create_by, create_time)
VALUES (1, '系统维护通知', '1', '今晚10点进行系统维护', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO sys_notice (notice_id, notice_title, notice_type, notice_content, status, create_by, create_time)
VALUES (2, '功能更新公告', '2', '新版本已上线', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO sys_notice (notice_id, notice_title, notice_type, notice_content, status, create_by, create_time, update_by, update_time, remark)
VALUES (3, '旧公告', '1', '已过期内容', '1', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, '已停用');

INSERT INTO sys_notice (notice_id, notice_title, notice_type, notice_content, status, create_by, create_time, update_by, update_time, remark)
VALUES (4, '新功能公告', '1', '新功能已上线', '0', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, '最新通知');

ALTER TABLE sys_notice ALTER COLUMN notice_id RESTART WITH 100;
