-- =====================================================================
-- H2 (MODE=Oracle) 建表 + 种子脚本：sys_role / sys_dept
-- 列集对照生产 flyway 脚本 db/migration/h2/V1__init_system.sql
-- 使用 H2 2.x Oracle 模式兼容语法：GENERATED BY DEFAULT AS IDENTITY
-- =====================================================================

CREATE TABLE sys_role (
    role_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name          VARCHAR(30) NOT NULL,
    role_key           VARCHAR(100),
    role_sort          INT,
    data_scope         CHAR(1),
    menu_check_strictly CHAR(1),
    dept_check_strictly CHAR(1),
    status             CHAR(1) DEFAULT '0',
    del_flag           CHAR(1) DEFAULT '0',
    create_by          VARCHAR(64),
    create_time        TIMESTAMP,
    update_by          VARCHAR(64),
    update_time        TIMESTAMP,
    remark             VARCHAR(500),
    version            BIGINT DEFAULT 0
);

CREATE TABLE sys_dept (
    dept_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    ancestors   VARCHAR(500),
    dept_name   VARCHAR(30) NOT NULL,
    order_num   INT,
    leader      VARCHAR(20),
    phone       VARCHAR(20),
    email       VARCHAR(50),
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_by   VARCHAR(64),
    create_time TIMESTAMP,
    update_by   VARCHAR(64),
    update_time TIMESTAMP,
    version     BIGINT DEFAULT 0
);

CREATE TABLE sys_user (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id     BIGINT,
    user_name   VARCHAR(30),
    nick_name   VARCHAR(30),
    password    VARCHAR(100),
    status      CHAR(1) DEFAULT '0',
    del_flag    CHAR(1) DEFAULT '0',
    create_time TIMESTAMP,
    version     BIGINT DEFAULT 0
);

CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id BIGINT
);

-- ---------------------------------------------------------------------
-- 种子数据：多种 status 用于过滤测试
-- ---------------------------------------------------------------------
INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (1, '超级管理员', 'admin', 1, '1', '0', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (2, '普通角色', 'common', 2, '2', '0', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (3, '停用角色', 'disabled_role', 3, '2', '1', '0');

INSERT INTO sys_role (role_id, role_name, role_key, role_sort, data_scope, status, del_flag)
VALUES (4, '已删除角色', 'deleted_role', 4, '2', '0', '2');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, leader, status, del_flag)
VALUES (100, 0, '0', '研发部', 1, '张三', '0', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, leader, status, del_flag)
VALUES (101, 100, '0,100', '研发一组', 1, '李四', '0', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, leader, status, del_flag)
VALUES (102, 100, '0,100', '研发二组', 2, '王五', '1', '0');

INSERT INTO sys_dept (dept_id, parent_id, ancestors, dept_name, order_num, leader, status, del_flag)
VALUES (200, 0, '0', '运维部', 2, '赵六', '0', '0');

-- identity 序列推到种子之后（导数迁移后同样要对齐）
ALTER TABLE sys_role ALTER COLUMN role_id RESTART WITH 1000;
ALTER TABLE sys_dept ALTER COLUMN dept_id RESTART WITH 1000;
ALTER TABLE sys_user ALTER COLUMN user_id RESTART WITH 1000;
