// 由 Maven pom.xml 平移生成（依赖坐标与作用域一一对应）

plugins {
    id 'scaffold.java-conventions'
}

dependencies {
    api project(':scaffold-api-job')
    api project(':scaffold-spring-boot-starter-cache')
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.apache.dubbo:dubbo'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation project(':scaffold-spring-boot-starter-test')
}
