// 由 Maven pom.xml 平移生成（依赖坐标与作用域一一对应）

plugins {
    id 'scaffold.boot-conventions'
}

dependencies {
    api 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery'
    api 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config'
    api 'com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel'
    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'org.springframework.boot:spring-boot-starter-quartz'
    api project(':scaffold-common-log')
    api project(':scaffold-api-job')
    api 'org.apache.dubbo:dubbo-rest-openapi'
    api 'org.flywaydb:flyway-core'
    testImplementation project(':scaffold-spring-boot-starter-test')
    runtimeOnly 'com.h2database:h2'
}
