-- =====================================================================
-- scaffold-message 消息中心 Flyway 基线（MESSAGE_DB，docs/消息中心模块设计文档.md §5）
-- 8 张表 + COMMENT + 索引 + 字典 INSERT（字典跨 schema 写 SYSTEM_DB，与 scaffold-system 现有方式一致）
-- 约定：主键应用层雪花 ID（NUMBER(20)，不建 IDENTITY，与 scaffold-audit 一致）；
--       兼容达梦 DM8（Oracle 兼容模式），不用 Oracle 专有语法。
-- =====================================================================

-- 1）短信渠道表
CREATE TABLE MESSAGE_DB.msg_sms_channel (
    ID            NUMBER(20)     NOT NULL,
    CHANNEL_NAME  VARCHAR2(64)   NOT NULL,
    CHANNEL_TYPE  VARCHAR2(20)   NOT NULL,
    ACCESS_KEY    VARCHAR2(128)  DEFAULT '',
    SECRET_KEY    VARCHAR2(256)  DEFAULT '',
    SIGN_NAME     VARCHAR2(64)   DEFAULT '',
    ENDPOINT      VARCHAR2(128)  DEFAULT NULL,
    REGION        VARCHAR2(64)   DEFAULT NULL,
    PRIORITY      NUMBER(4)      DEFAULT 1,
    STATUS        CHAR(1)        DEFAULT '0',
    DEL_FLAG      CHAR(1)        DEFAULT '0',
    CREATE_BY     VARCHAR2(64)   DEFAULT '',
    CREATE_TIME   TIMESTAMP(0),
    UPDATE_BY     VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME   TIMESTAMP(0),
    REMARK        VARCHAR2(255)  DEFAULT NULL,
    VERSION       NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_SMS_CHANNEL PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_SMS_CHANNEL_NAME UNIQUE (CHANNEL_NAME)
);
COMMENT ON TABLE MESSAGE_DB.msg_sms_channel IS '短信渠道表（厂商账号配置，同类型可多渠道按优先级failover）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_channel.CHANNEL_TYPE IS '类型：ALIYUN/TENCENT/HUAWEI/CTYUN/MOCK（字典message_sms_channel_type）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_channel.SECRET_KEY IS '厂商SecretKey（SM4密文，列表脱敏不回显）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_channel.PRIORITY IS '优先级（小者先用，同类型failover）';
CREATE INDEX MESSAGE_DB.IDX_MSG_SMS_CHANNEL_TYPE ON MESSAGE_DB.msg_sms_channel (CHANNEL_TYPE, STATUS);

-- 2）短信模板表
CREATE TABLE MESSAGE_DB.msg_sms_template (
    ID               NUMBER(20)     NOT NULL,
    TEMPLATE_CODE    VARCHAR2(64)   NOT NULL,
    TEMPLATE_NAME    VARCHAR2(64)   NOT NULL,
    CHANNEL_ID       NUMBER(20),
    TEMPLATE_MODE    CHAR(1)        DEFAULT '0',
    VENDOR_CODE      VARCHAR2(64),
    SIGN_NAME        VARCHAR2(64),
    TEMPLATE_CONTENT VARCHAR2(1000) NOT NULL,
    PARAM_NAMES      VARCHAR2(512),
    CATEGORY         VARCHAR2(20),
    STATUS           CHAR(1)        DEFAULT '0',
    DEL_FLAG         CHAR(1)        DEFAULT '0',
    CREATE_BY        VARCHAR2(64)   DEFAULT '',
    CREATE_TIME      TIMESTAMP(0),
    UPDATE_BY        VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME      TIMESTAMP(0),
    REMARK           VARCHAR2(255)  DEFAULT NULL,
    VERSION          NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_SMS_TEMPLATE PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_SMS_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);
COMMENT ON TABLE MESSAGE_DB.msg_sms_template IS '短信模板表（占位符${key}，双轨：本平台渲染整文/厂商模板code+参数）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_template.TEMPLATE_MODE IS '模板模式：0本平台渲染整文 1厂商模板code+参数';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_template.PARAM_NAMES IS '变量名清单（逗号分隔，录入时解析生成，发送校验用）';

-- 3）短信发送日志表
CREATE TABLE MESSAGE_DB.msg_sms_log (
    ID              NUMBER(20)     NOT NULL,
    TEMPLATE_ID     NUMBER(20),
    TEMPLATE_CODE   VARCHAR2(64)   NOT NULL,
    CHANNEL_ID      NUMBER(20),
    CHANNEL_TYPE    VARCHAR2(20),
    MOBILE          VARCHAR2(20)   NOT NULL,
    SIGN_NAME       VARCHAR2(64),
    CONTENT         VARCHAR2(1000),
    PARAM_JSON      VARCHAR2(2000),
    SEND_STATUS     VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    CHANNEL_MSG_ID  VARCHAR2(64),
    FAIL_REASON     VARCHAR2(512),
    RETRY_COUNT     NUMBER(4)      DEFAULT 0,
    SEND_TIME       TIMESTAMP(0),
    RECEIPT_TIME    TIMESTAMP(0),
    BIZ_TYPE        VARCHAR2(32),
    BIZ_ID          VARCHAR2(64),
    IDEMPOTENT_KEY  VARCHAR2(64),
    CREATE_BY       VARCHAR2(64)   DEFAULT '',
    CREATE_TIME     TIMESTAMP(0),
    UPDATE_BY       VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME     TIMESTAMP(0),
    REMARK          VARCHAR2(255)  DEFAULT NULL,
    VERSION         NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_SMS_LOG PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_SMS_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
);
COMMENT ON TABLE MESSAGE_DB.msg_sms_log IS '短信发送日志（状态机PENDING→SENDING→SUCCESS/FAILED，回执可负向修正）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_log.SEND_STATUS IS 'PENDING/SENDING/SUCCESS/FAILED（字典message_send_status）';
COMMENT ON COLUMN MESSAGE_DB.msg_sms_log.CHANNEL_MSG_ID IS '通道方消息ID（回执对账键）';
CREATE INDEX MESSAGE_DB.IDX_MSG_SMS_LOG_SEND_TIME ON MESSAGE_DB.msg_sms_log (SEND_TIME);
CREATE INDEX MESSAGE_DB.IDX_MSG_SMS_LOG_MOBILE ON MESSAGE_DB.msg_sms_log (MOBILE, SEND_TIME);
CREATE INDEX MESSAGE_DB.IDX_MSG_SMS_LOG_STATUS ON MESSAGE_DB.msg_sms_log (SEND_STATUS, SEND_TIME);
CREATE INDEX MESSAGE_DB.IDX_MSG_SMS_LOG_MSG_ID ON MESSAGE_DB.msg_sms_log (CHANNEL_MSG_ID);

-- 4）邮箱账号表
CREATE TABLE MESSAGE_DB.msg_mail_account (
    ID           NUMBER(20)     NOT NULL,
    ACCOUNT_NAME VARCHAR2(64)   NOT NULL,
    EMAIL_ADDR   VARCHAR2(128)  NOT NULL,
    SMTP_HOST    VARCHAR2(128)  NOT NULL,
    SMTP_PORT    NUMBER(6),
    SMTP_SSL     CHAR(1)        DEFAULT '1',
    AUTH_USER    VARCHAR2(128)  NOT NULL,
    AUTH_CODE    VARCHAR2(256)  NOT NULL,
    NICK_NAME    VARCHAR2(64),
    DAILY_LIMIT  NUMBER(6)      DEFAULT 0,
    STATUS       CHAR(1)        DEFAULT '0',
    DEL_FLAG     CHAR(1)        DEFAULT '0',
    CREATE_BY    VARCHAR2(64)   DEFAULT '',
    CREATE_TIME  TIMESTAMP(0),
    UPDATE_BY    VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME  TIMESTAMP(0),
    REMARK       VARCHAR2(255)  DEFAULT NULL,
    VERSION      NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_MAIL_ACCOUNT PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_MAIL_ACCOUNT_ADDR UNIQUE (EMAIL_ADDR)
);
COMMENT ON TABLE MESSAGE_DB.msg_mail_account IS '邮箱账号表（SMTP发件账号，授权码SM4密文）';
COMMENT ON COLUMN MESSAGE_DB.msg_mail_account.AUTH_CODE IS '授权码/密码（SM4密文，列表脱敏不回显，编辑留空即不改）';
COMMENT ON COLUMN MESSAGE_DB.msg_mail_account.DAILY_LIMIT IS '日发送上限（0不限），超限拒发';

-- 5）邮件模板表
CREATE TABLE MESSAGE_DB.msg_mail_template (
    ID               NUMBER(20)     NOT NULL,
    TEMPLATE_CODE    VARCHAR2(64)   NOT NULL,
    TEMPLATE_NAME    VARCHAR2(64)   NOT NULL,
    ACCOUNT_ID       NUMBER(20),
    SUBJECT          VARCHAR2(200)  NOT NULL,
    TEMPLATE_CONTENT CLOB           NOT NULL,
    IS_HTML          CHAR(1)        DEFAULT '1',
    PARAM_NAMES      VARCHAR2(512),
    CATEGORY         VARCHAR2(20),
    STATUS           CHAR(1)        DEFAULT '0',
    DEL_FLAG         CHAR(1)        DEFAULT '0',
    CREATE_BY        VARCHAR2(64)   DEFAULT '',
    CREATE_TIME      TIMESTAMP(0),
    UPDATE_BY        VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME      TIMESTAMP(0),
    REMARK           VARCHAR2(255)  DEFAULT NULL,
    VERSION          NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_MAIL_TEMPLATE PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_MAIL_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);
COMMENT ON TABLE MESSAGE_DB.msg_mail_template IS '邮件模板表（HTML富文本，主题与正文支持${key}）';

-- 6）邮件发送记录表
CREATE TABLE MESSAGE_DB.msg_mail_log (
    ID              NUMBER(20)     NOT NULL,
    TEMPLATE_ID     NUMBER(20),
    TEMPLATE_CODE   VARCHAR2(64),
    ACCOUNT_ID      NUMBER(20),
    TO_ADDRS        VARCHAR2(1000) NOT NULL,
    CC_ADDRS        VARCHAR2(1000),
    SUBJECT         VARCHAR2(200),
    CONTENT         CLOB,
    IS_HTML         CHAR(1)        DEFAULT '1',
    ATTACH_FILE_IDS VARCHAR2(500),
    SEND_STATUS     VARCHAR2(16)   DEFAULT 'PENDING' NOT NULL,
    FAIL_REASON     VARCHAR2(512),
    RETRY_COUNT     NUMBER(4)      DEFAULT 0,
    SEND_TIME       TIMESTAMP(0),
    BIZ_TYPE        VARCHAR2(32),
    BIZ_ID          VARCHAR2(64),
    IDEMPOTENT_KEY  VARCHAR2(64),
    CREATE_BY       VARCHAR2(64)   DEFAULT '',
    CREATE_TIME     TIMESTAMP(0),
    UPDATE_BY       VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME     TIMESTAMP(0),
    REMARK          VARCHAR2(255)  DEFAULT NULL,
    VERSION         NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_MAIL_LOG PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_MAIL_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
);
COMMENT ON TABLE MESSAGE_DB.msg_mail_log IS '邮件发送记录（SMTP异常即终态，无回执链路）';
COMMENT ON COLUMN MESSAGE_DB.msg_mail_log.ATTACH_FILE_IDS IS '附件fileId列表（ct-file，逗号分隔≤10）';
CREATE INDEX MESSAGE_DB.IDX_MSG_MAIL_LOG_SEND_TIME ON MESSAGE_DB.msg_mail_log (SEND_TIME);
CREATE INDEX MESSAGE_DB.IDX_MSG_MAIL_LOG_STATUS ON MESSAGE_DB.msg_mail_log (SEND_STATUS, SEND_TIME);

-- 7）站内信模板表
CREATE TABLE MESSAGE_DB.msg_inner_template (
    ID                NUMBER(20)     NOT NULL,
    TEMPLATE_CODE     VARCHAR2(64)   NOT NULL,
    TEMPLATE_NAME     VARCHAR2(64)   NOT NULL,
    TITLE             VARCHAR2(100)  NOT NULL,
    TEMPLATE_CONTENT  VARCHAR2(2000) NOT NULL,
    MISSING_PARAM_MODE CHAR(1)       DEFAULT '0',
    JUMP_URL          VARCHAR2(256),
    PARAM_NAMES       VARCHAR2(512),
    CATEGORY          VARCHAR2(20),
    STATUS            CHAR(1)        DEFAULT '0',
    DEL_FLAG          CHAR(1)        DEFAULT '0',
    CREATE_BY         VARCHAR2(64)   DEFAULT '',
    CREATE_TIME       TIMESTAMP(0),
    UPDATE_BY         VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME       TIMESTAMP(0),
    REMARK            VARCHAR2(255)  DEFAULT NULL,
    VERSION           NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_INNER_TEMPLATE PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_INNER_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);
COMMENT ON TABLE MESSAGE_DB.msg_inner_template IS '站内信模板表（点对点，与广播型公告互补）';
COMMENT ON COLUMN MESSAGE_DB.msg_inner_template.MISSING_PARAM_MODE IS '缺参策略：0报错 1保留占位 2置空';
COMMENT ON COLUMN MESSAGE_DB.msg_inner_template.JUMP_URL IS '点击跳转路由（前端站内路由，可空）';

-- 8）站内信消息记录表
CREATE TABLE MESSAGE_DB.msg_inner_message (
    ID              NUMBER(20)     NOT NULL,
    TEMPLATE_ID     NUMBER(20),
    TEMPLATE_CODE   VARCHAR2(64),
    TITLE           VARCHAR2(100)  NOT NULL,
    CONTENT         VARCHAR2(2000) NOT NULL,
    JUMP_URL        VARCHAR2(256),
    RECEIVER_ID     NUMBER(20)     NOT NULL,
    RECEIVER_NAME   VARCHAR2(64),
    READ_FLAG       CHAR(1)        DEFAULT '0',
    READ_TIME       TIMESTAMP(0),
    SENDER_TYPE     CHAR(1)        DEFAULT '0',
    SENDER_ID       NUMBER(20),
    SENDER_NAME     VARCHAR2(64),
    BIZ_TYPE        VARCHAR2(32),
    BIZ_ID          VARCHAR2(64),
    IDEMPOTENT_KEY  VARCHAR2(64),
    CREATE_BY       VARCHAR2(64)   DEFAULT '',
    CREATE_TIME     TIMESTAMP(0),
    UPDATE_BY       VARCHAR2(64)   DEFAULT '',
    UPDATE_TIME     TIMESTAMP(0),
    REMARK          VARCHAR2(255)  DEFAULT NULL,
    VERSION         NUMBER(10)     DEFAULT 0,
    CONSTRAINT PK_MSG_INNER_MESSAGE PRIMARY KEY (ID),
    CONSTRAINT UK_MSG_INNER_MSG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, RECEIVER_ID, IDEMPOTENT_KEY)
);
COMMENT ON TABLE MESSAGE_DB.msg_inner_message IS '站内信消息记录（按接收人一行一条，含已读状态）';
COMMENT ON COLUMN MESSAGE_DB.msg_inner_message.RECEIVER_NAME IS '冗余姓名（列表免关联）';
COMMENT ON COLUMN MESSAGE_DB.msg_inner_message.READ_FLAG IS '0未读 1已读（字典message_read_flag）';
COMMENT ON COLUMN MESSAGE_DB.msg_inner_message.SENDER_TYPE IS '0系统自动 1人工';
CREATE INDEX MESSAGE_DB.IDX_MSG_INNER_MSG_UNREAD ON MESSAGE_DB.msg_inner_message (RECEIVER_ID, READ_FLAG);
CREATE INDEX MESSAGE_DB.IDX_MSG_INNER_MSG_RECENT ON MESSAGE_DB.msg_inner_message (RECEIVER_ID, CREATE_TIME);
