-- 定时任务建表 + 种子数据
-- status: 0=正常 1=暂停
-- concurrent: 0=允许并发 1=禁止并发
-- misfire_policy: 1=立即执行 2=执行一次 3=放弃执行
CREATE TABLE sys_job (
    job_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name         VARCHAR(100),
    job_group        VARCHAR(100) DEFAULT 'DEFAULT',
    invoke_target   VARCHAR(500),
    cron_expression VARCHAR(100),
    misfire_policy  VARCHAR(20) DEFAULT '1',
    concurrent      CHAR(1) DEFAULT '1',
    status          CHAR(1) DEFAULT '0',
    create_by       VARCHAR(64),
    create_time     TIMESTAMP,
    update_by       VARCHAR(64),
    update_time     TIMESTAMP,
    remark          VARCHAR(500),
    version         BIGINT DEFAULT 0
);

INSERT INTO sys_job (job_id, job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark, version)
VALUES (1, '数据清理任务', 'DEFAULT', 'DataCleanJob', '0 0 2 * * ?', '1', '1', '0', 'admin', CURRENT_TIMESTAMP, '每天凌晨2点执行', 1);

INSERT INTO sys_job (job_id, job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark, version)
VALUES (2, '报表汇总任务', 'SYSTEM', 'ReportJob', '0 0 3 * * ?', '2', '0', '1', 'admin', CURRENT_TIMESTAMP, '每天凌晨3点执行（暂停）', 1);

INSERT INTO sys_job (job_id, job_name, job_group, invoke_target, cron_expression, misfire_policy, concurrent, status, create_by, create_time, remark, version)
VALUES (3, '健康检查', 'DEFAULT', 'HealthCheckJob', '0/30 * * * * ?', '1', '1', '0', 'admin', CURRENT_TIMESTAMP, '每30秒检查一次', 1);

ALTER TABLE sys_job ALTER COLUMN job_id RESTART WITH 100;
