-- 定时任务日志建表 + 种子数据
-- status: 0=正常 1=失败
CREATE TABLE sys_job_log (
    job_log_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name       VARCHAR(100),
    job_group      VARCHAR(100),
    invoke_target  VARCHAR(500),
    job_message    VARCHAR(1000),
    status         CHAR(1),
    exception_info VARCHAR(2000),
    start_time     TIMESTAMP,
    end_time       TIMESTAMP,
    create_by      VARCHAR(64),
    create_time    TIMESTAMP,
    update_by      VARCHAR(64),
    update_time    TIMESTAMP,
    remark         VARCHAR(500)
);

INSERT INTO sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, start_time, end_time, create_time)
VALUES (1, '数据清理任务', 'DEFAULT', 'DataCleanJob', '开始执行数据清理', '0', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, exception_info, start_time, end_time, create_time)
VALUES (2, '报表汇总任务', 'SYSTEM', 'ReportJob', '执行失败', '1', 'Connection timeout', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO sys_job_log (job_log_id, job_name, job_group, invoke_target, job_message, status, start_time, end_time, create_time)
VALUES (3, '健康检查', 'DEFAULT', 'HealthCheckJob', '健康检查完成', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE sys_job_log ALTER COLUMN job_log_id RESTART WITH 100;
