-- services/job sqlserver 方言家族基线（由 scripts/gen_dialect_migrations.py 从 h2 基线生成，勿手工编辑；
-- GENERATED-BY gen_dialect_migrations.py
-- 修正应改脚本映射表后 --force 重新生成；真实库接入回归见 docs/multi-database-guide.md §6）

-- ============================================================================
-- Oracle 版本: V1__init_quartz.sql
-- 转换自: ct-modules/scaffold-job/src/main/resources/db/migration/V1__init_quartz.sql
-- 说明: Quartz 调度表（Oracle 兼容版本）
--   1. VARCHAR → VARCHAR2, BIGINT → NUMBER, BLOB → BLOB 保持不变
--   2. 外键语法在 Oracle 中稍有不同
--   3. ENGINE=InnoDB 在 Oracle 中不需要
-- ============================================================================

-- 1、任务详细信息表

CREATE TABLE QRTZ_JOB_DETAILS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    JOB_NAME NVARCHAR(200) NOT NULL,
    JOB_GROUP NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(250),
    JOB_CLASS_NAME NVARCHAR(250) NOT NULL,
    IS_DURABLE NVARCHAR(1) NOT NULL,
    IS_NONCONCURRENT NVARCHAR(1) NOT NULL,
    IS_UPDATE_DATA NVARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY NVARCHAR(1) NOT NULL,
    JOB_DATA VARBINARY(MAX),
    CONSTRAINT PK_QRTZ_JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'任务详细信息表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_JOB_DETAILS';

-- 2、触发器详细信息表

CREATE TABLE QRTZ_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    JOB_NAME NVARCHAR(200) NOT NULL,
    JOB_GROUP NVARCHAR(200) NOT NULL,
    DESCRIPTION NVARCHAR(250),
    NEXT_FIRE_TIME BIGINT,
    PREV_FIRE_TIME BIGINT,
    PRIORITY INTEGER,
    TRIGGER_STATE NVARCHAR(16) NOT NULL,
    TRIGGER_TYPE NVARCHAR(8) NOT NULL,
    START_TIME BIGINT NOT NULL,
    END_TIME BIGINT,
    CALENDAR_NAME NVARCHAR(200),
    MISFIRE_INSTR SMALLINT,
    JOB_DATA VARBINARY(MAX),
    CONSTRAINT PK_QRTZ_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'触发器详细信息表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_TRIGGERS';

-- 外键
ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT FK_QRTZ_TRIGGERS_JD
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP);

-- 3、简单触发器信息表

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    REPEAT_COUNT INT NOT NULL,
    REPEAT_INTERVAL BIGINT NOT NULL,
    TIMES_TRIGGERED BIGINT NOT NULL,
    CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPLE_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 4、Cron 触发器表

CREATE TABLE QRTZ_CRON_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    CRON_EXPRESSION NVARCHAR(200) NOT NULL,
    TIME_ZONE_ID NVARCHAR(80),
    CONSTRAINT PK_QRTZ_CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT FK_QRTZ_CRON_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 5、Blob 类型触发器表

CREATE TABLE QRTZ_BLOB_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    BLOB_DATA VARBINARY(MAX),
    CONSTRAINT PK_QRTZ_BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE QRTZ_BLOB_TRIGGERS ADD CONSTRAINT FK_QRTZ_BLOB_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

-- 6、日历信息表

CREATE TABLE QRTZ_CALENDARS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    CALENDAR_NAME NVARCHAR(200) NOT NULL,
    CALENDAR VARBINARY(MAX) NOT NULL,
    CONSTRAINT PK_QRTZ_CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'日历信息表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_CALENDARS';

-- 7、暂停的触发器表

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'暂停的触发器表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_PAUSED_TRIGGER_GRPS';

-- 8、已触发的触发器表

CREATE TABLE QRTZ_FIRED_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    ENTRY_ID NVARCHAR(95) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    INSTANCE_NAME NVARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT NOT NULL,
    SCHED_TIME BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE NVARCHAR(16) NOT NULL,
    JOB_NAME NVARCHAR(200),
    JOB_GROUP NVARCHAR(200),
    IS_NONCONCURRENT NVARCHAR(1),
    REQUESTS_RECOVERY NVARCHAR(1),
    CONSTRAINT PK_QRTZ_FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'已触发的触发器表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_FIRED_TRIGGERS';

-- 9、调度器状态表

CREATE TABLE QRTZ_SCHEDULER_STATE (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    INSTANCE_NAME NVARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT NOT NULL,
    CHECKIN_INTERVAL BIGINT NOT NULL,
    CONSTRAINT PK_QRTZ_SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'调度器状态表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_SCHEDULER_STATE';

-- 10、悲观锁信息表

CREATE TABLE QRTZ_LOCKS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    LOCK_NAME NVARCHAR(40) NOT NULL,
    CONSTRAINT PK_QRTZ_LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
EXEC sp_addextendedproperty @name=N'MS_Description', @value=N'存储的悲观锁信息表', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'QRTZ_LOCKS';

-- 11、同步机制的行锁表

CREATE TABLE QRTZ_SIMPROP_TRIGGERS (
    SCHED_NAME NVARCHAR(120) NOT NULL,
    TRIGGER_NAME NVARCHAR(200) NOT NULL,
    TRIGGER_GROUP NVARCHAR(200) NOT NULL,
    STR_PROP_1 NVARCHAR(512),
    STR_PROP_2 NVARCHAR(512),
    STR_PROP_3 NVARCHAR(512),
    INT_PROP_1 INTEGER,
    INT_PROP_2 INTEGER,
    LONG_PROP_1 DECIMAL(20,0),
    LONG_PROP_2 DECIMAL(20,0),
    DEC_PROP_1 DECIMAL(13,4),
    DEC_PROP_2 DECIMAL(13,4),
    BOOL_PROP_1 NVARCHAR(1),
    BOOL_PROP_2 NVARCHAR(1),
    CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
);
ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT FK_QRTZ_SIMPROP_TG
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP);

COMMIT;

-- ===================================================================
-- 以下并入原 V2__init_job_data.sql（占位）与 V3__create_sys_job_tables.sql（2026-09 合并为单基线）
-- 定时任务初始化数据：暂无生效语句；Quartz 持久化 Job 注册示例注释见原 V2__init_job_data.sql（已并入）


-- ===================================================================

CREATE TABLE SYS_JOB (
    JOB_ID BIGINT IDENTITY(100,1),
    JOB_NAME NVARCHAR(64) DEFAULT '',
    JOB_GROUP NVARCHAR(64) DEFAULT 'DEFAULT',
    INVOKE_TARGET NVARCHAR(500) NOT NULL,
    CRON_EXPRESSION NVARCHAR(255) DEFAULT '',
    MISFIRE_POLICY NVARCHAR(20) DEFAULT '3',
    CONCURRENT NCHAR(1) DEFAULT '1',
    STATUS NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2(0),
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2(0),
    REMARK NVARCHAR(500) DEFAULT '',
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT PK_SYS_JOB PRIMARY KEY (JOB_ID, JOB_NAME, JOB_GROUP)
);


CREATE TABLE SYS_JOB_LOG (
    JOB_LOG_ID BIGINT IDENTITY(100,1),
    JOB_NAME NVARCHAR(64) NOT NULL,
    JOB_GROUP NVARCHAR(64) NOT NULL,
    INVOKE_TARGET NVARCHAR(500) NOT NULL,
    JOB_MESSAGE NVARCHAR(500),
    STATUS NCHAR(1) DEFAULT '0',
    EXCEPTION_INFO NVARCHAR(2000) DEFAULT '',
    START_TIME DATETIME2(0),
    END_TIME DATETIME2(0),
    CREATE_TIME DATETIME2(0),
    CONSTRAINT PK_SYS_JOB_LOG PRIMARY KEY (JOB_LOG_ID)
);
