// 由 Maven pom.xml 平移生成（依赖坐标与作用域一一对应）

plugins {
    id 'scaffold.java-conventions'
}

dependencies {
    api 'org.apache.dubbo:dubbo-spring-boot-starter'
    api 'org.apache.dubbo:dubbo-nacos-spring-boot-starter'
    api 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    api 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
    api 'org.springframework:spring-web'
    api 'org.springframework:spring-context-support'
    api 'com.alibaba:transmittable-thread-local'
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'com.fasterxml.jackson.core:jackson-databind'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api 'com.alibaba.fastjson2:fastjson2'
    api 'io.jsonwebtoken:jjwt-api'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson'
    api 'javax.xml.bind:jaxb-api'
    api 'org.apache.commons:commons-lang3'
    api 'commons-io:commons-io'
    api 'org.apache.poi:poi-ooxml'
    api 'jakarta.servlet:jakarta.servlet-api'
    api 'jakarta.validation:jakarta.validation-api'
    api 'org.bouncycastle:bcprov-jdk18on'
    api 'org.mapstruct:mapstruct'
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
