-- services/message sqlserver 方言家族基线（由 scripts/gen_dialect_migrations.py 从 h2 基线生成，勿手工编辑；
-- GENERATED-BY gen_dialect_migrations.py
-- 修正应改脚本映射表后 --force 重新生成；真实库接入回归见 docs/multi-database-guide.md §6）

-- 本地 H2 基线（对照 db/migration/oracle/V1__baseline.sql，H2 方言，去 schema 前缀）
-- 另建 SYSTEM_DB 模拟 schema（sys_user/sys_role/sys_user_role），供 UserDirectoryMapper 接收范围展开


CREATE TABLE msg_sms_channel (
    ID BIGINT,
    PRIMARY KEY (ID),
    CHANNEL_NAME NVARCHAR(64) NOT NULL,
    CHANNEL_TYPE NVARCHAR(20) NOT NULL,
    ACCESS_KEY NVARCHAR(128) DEFAULT '',
    SECRET_KEY NVARCHAR(256) DEFAULT '',
    SIGN_NAME NVARCHAR(64) DEFAULT '',
    ENDPOINT NVARCHAR(128),
    REGION NVARCHAR(64),
    PRIORITY INT DEFAULT 1,
    STATUS NCHAR(1) DEFAULT '0',
    DEL_FLAG NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_CHANNEL_NAME UNIQUE (CHANNEL_NAME)
);
CREATE INDEX IDX_MSG_SMS_CHANNEL_TYPE ON msg_sms_channel (CHANNEL_TYPE, STATUS);


CREATE TABLE msg_sms_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE NVARCHAR(64) NOT NULL,
    TEMPLATE_NAME NVARCHAR(64) NOT NULL,
    CHANNEL_ID BIGINT,
    TEMPLATE_MODE NCHAR(1) DEFAULT '0',
    VENDOR_CODE NVARCHAR(64),
    SIGN_NAME NVARCHAR(64),
    TEMPLATE_CONTENT NVARCHAR(1000) NOT NULL,
    PARAM_NAMES NVARCHAR(512),
    CATEGORY NVARCHAR(20),
    STATUS NCHAR(1) DEFAULT '0',
    DEL_FLAG NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);


CREATE TABLE msg_sms_log (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE NVARCHAR(64) NOT NULL,
    CHANNEL_ID BIGINT,
    CHANNEL_TYPE NVARCHAR(20),
    MOBILE NVARCHAR(20) NOT NULL,
    SIGN_NAME NVARCHAR(64),
    CONTENT NVARCHAR(1000),
    PARAM_JSON NVARCHAR(2000),
    SEND_STATUS NVARCHAR(16) NOT NULL DEFAULT 'PENDING',
    CHANNEL_MSG_ID NVARCHAR(64),
    FAIL_REASON NVARCHAR(512),
    RETRY_COUNT INT DEFAULT 0,
    SEND_TIME DATETIME2,
    RECEIPT_TIME DATETIME2,
    BIZ_TYPE NVARCHAR(32),
    BIZ_ID NVARCHAR(64),
    IDEMPOTENT_KEY NVARCHAR(64),
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_SMS_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
);
CREATE INDEX IDX_MSG_SMS_LOG_SEND_TIME ON msg_sms_log (SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_MOBILE ON msg_sms_log (MOBILE, SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_STATUS ON msg_sms_log (SEND_STATUS, SEND_TIME);
CREATE INDEX IDX_MSG_SMS_LOG_MSG_ID ON msg_sms_log (CHANNEL_MSG_ID);


CREATE TABLE msg_mail_account (
    ID BIGINT,
    PRIMARY KEY (ID),
    ACCOUNT_NAME NVARCHAR(64) NOT NULL,
    EMAIL_ADDR NVARCHAR(128) NOT NULL,
    SMTP_HOST NVARCHAR(128) NOT NULL,
    SMTP_PORT INT,
    SMTP_SSL NCHAR(1) DEFAULT '1',
    AUTH_USER NVARCHAR(128) NOT NULL,
    AUTH_CODE NVARCHAR(256) NOT NULL,
    NICK_NAME NVARCHAR(64),
    DAILY_LIMIT INT DEFAULT 0,
    STATUS NCHAR(1) DEFAULT '0',
    DEL_FLAG NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_ACCOUNT_ADDR UNIQUE (EMAIL_ADDR)
);


CREATE TABLE msg_mail_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE NVARCHAR(64) NOT NULL,
    TEMPLATE_NAME NVARCHAR(64) NOT NULL,
    ACCOUNT_ID BIGINT,
    SUBJECT NVARCHAR(200) NOT NULL,
    TEMPLATE_CONTENT NVARCHAR(MAX) NOT NULL,
    IS_HTML NCHAR(1) DEFAULT '1',
    PARAM_NAMES NVARCHAR(512),
    CATEGORY NVARCHAR(20),
    STATUS NCHAR(1) DEFAULT '0',
    DEL_FLAG NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);


CREATE TABLE msg_mail_log (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE NVARCHAR(64),
    ACCOUNT_ID BIGINT,
    TO_ADDRS NVARCHAR(1000) NOT NULL,
    CC_ADDRS NVARCHAR(1000),
    SUBJECT NVARCHAR(200),
    CONTENT NVARCHAR(MAX),
    IS_HTML NCHAR(1) DEFAULT '1',
    ATTACH_FILE_IDS NVARCHAR(500),
    SEND_STATUS NVARCHAR(16) NOT NULL DEFAULT 'PENDING',
    FAIL_REASON NVARCHAR(512),
    RETRY_COUNT INT DEFAULT 0,
    SEND_TIME DATETIME2,
    BIZ_TYPE NVARCHAR(32),
    BIZ_ID NVARCHAR(64),
    IDEMPOTENT_KEY NVARCHAR(64),
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_MAIL_LOG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, IDEMPOTENT_KEY)
);
CREATE INDEX IDX_MSG_MAIL_LOG_SEND_TIME ON msg_mail_log (SEND_TIME);
CREATE INDEX IDX_MSG_MAIL_LOG_STATUS ON msg_mail_log (SEND_STATUS, SEND_TIME);


CREATE TABLE msg_inner_template (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_CODE NVARCHAR(64) NOT NULL,
    TEMPLATE_NAME NVARCHAR(64) NOT NULL,
    TITLE NVARCHAR(100) NOT NULL,
    TEMPLATE_CONTENT NVARCHAR(2000) NOT NULL,
    MISSING_PARAM_MODE NCHAR(1) DEFAULT '0',
    JUMP_URL NVARCHAR(256),
    PARAM_NAMES NVARCHAR(512),
    CATEGORY NVARCHAR(20),
    STATUS NCHAR(1) DEFAULT '0',
    DEL_FLAG NCHAR(1) DEFAULT '0',
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_INNER_TEMPLATE_CODE UNIQUE (TEMPLATE_CODE)
);


CREATE TABLE msg_inner_message (
    ID BIGINT,
    PRIMARY KEY (ID),
    TEMPLATE_ID BIGINT,
    TEMPLATE_CODE NVARCHAR(64),
    TITLE NVARCHAR(100) NOT NULL,
    CONTENT NVARCHAR(2000) NOT NULL,
    JUMP_URL NVARCHAR(256),
    RECEIVER_ID BIGINT NOT NULL,
    RECEIVER_NAME NVARCHAR(64),
    READ_FLAG NCHAR(1) DEFAULT '0',
    READ_TIME DATETIME2,
    SENDER_TYPE NCHAR(1) DEFAULT '0',
    SENDER_ID BIGINT,
    SENDER_NAME NVARCHAR(64),
    BIZ_TYPE NVARCHAR(32),
    BIZ_ID NVARCHAR(64),
    IDEMPOTENT_KEY NVARCHAR(64),
    CREATE_BY NVARCHAR(64) DEFAULT '',
    CREATE_TIME DATETIME2,
    UPDATE_BY NVARCHAR(64) DEFAULT '',
    UPDATE_TIME DATETIME2,
    REMARK NVARCHAR(255),
    VERSION BIGINT DEFAULT 0,
    CONSTRAINT UK_MSG_INNER_MSG_IDEM UNIQUE (BIZ_TYPE, BIZ_ID, TEMPLATE_CODE, RECEIVER_ID, IDEMPOTENT_KEY)
);
CREATE INDEX IDX_MSG_INNER_MSG_UNREAD ON msg_inner_message (RECEIVER_ID, READ_FLAG);
CREATE INDEX IDX_MSG_INNER_MSG_RECENT ON msg_inner_message (RECEIVER_ID, CREATE_TIME);

-- SYSTEM_DB 模拟 schema（UserDirectoryMapper 接收范围展开，只读）

CREATE TABLE sys_user (
    user_id BIGINT,
    PRIMARY KEY (user_id),
    user_name NVARCHAR(64),
    nick_name NVARCHAR(64),
    status NCHAR(1) DEFAULT '0',
    del_flag NCHAR(1) DEFAULT '0'
);

CREATE TABLE sys_role (
    role_id BIGINT,
    PRIMARY KEY (role_id),
    role_key NVARCHAR(100),
    status NCHAR(1) DEFAULT '0',
    del_flag NCHAR(1) DEFAULT '0'
);

CREATE TABLE sys_user_role (
    user_id BIGINT,
    role_id BIGINT
);
